baseURL = "https://mattarnster.co.uk/"
languageCode = "en-us"
title = "mattarnster-blog"
theme = "hyde-hyde"
googleanalytics = "UA-18228344-1"

[params]
highlightjs = true
author = "Matt Arnold"
authorimage = "/images/matt.jpg"

[params.social]
github = "mattarnster"
instagram = "mattarnster"
twitter = "mattarnster"
email = "matt@mattarnster.co.uk"

[[menu.main]]
name = "Posts"
weight = 100
identifier = "posts"
url = "/posts/"
[[menu.main]]
name = "Portfolio"
identifier = "portfolio"
weight = 200
url = "/portfolio/"
[[menu.main]]
name = "About"
identifier = "about"
weight = 300
url = "/about/"
