baseURL = "https://mattarnster.co.uk/"
languageCode = "en-us"
title = "Matt Arnold"
theme = "anatole"
googleanalytics = "UA-18228344-1"

[params]
highlightjs = true
author = "Matt Arnold"
profilePicture = "/images/matt.jpg"
title = "Matt Arnold"
customCss = ["css/custom.css"]


[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/mattarnster"

[[params.socialIcons]]
icon = "fa-twitter"
title = "Twitter"
url = "https://twitter.com/mattarnster"

[[params.socialIcons]]
icon = "fa-envelope-o"
title = "Email"
url = "mailto:matt@mattarnster.co.uk"



[[menu.main]]
name = "Posts"
weight = 100
identifier = "posts"
url = "/posts/"
[[menu.main]]
name = "Portfolio"
identifier = "portfolio"
weight = 200
url = "/portfolio/"
[[menu.main]]
name = "About"
identifier = "about"
weight = 300
url = "/about/"
